import argparse
import json
import math
import re
import statistics
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import torch
import torch.nn as nn
from PIL import Image
from torch.utils.data import DataLoader, Dataset

from model import DetectionModule, SimilarityModule

try:
    from thop import profile as thop_profile
except ImportError:
    thop_profile = None

try:
    from fvcore.nn import FlopCountAnalysis
except ImportError:
    FlopCountAnalysis = None

try:
    from torchvision import transforms
    from torchvision.models import ResNet34_Weights, resnet34
    from torchvision.transforms import InterpolationMode
except ImportError:
    transforms = None
    ResNet34_Weights = None
    resnet34 = None
    InterpolationMode = None

try:
    from transformers import AutoModel, AutoTokenizer
except ImportError:
    AutoModel = None
    AutoTokenizer = None

try:
    from tflite_runtime.interpreter import Interpreter as TFLiteRuntimeInterpreter
except ImportError:
    TFLiteRuntimeInterpreter = None

try:
    import tensorflow as tf
except ImportError:
    tf = None


TASK_TEMPLATE = """The following are two questions about fake news detection.
News Caption: {}.
The key entities (such as people and places), event descriptions, and time information in the texts and images of real news should be consistent, without contradictions or the situation of being reused across different time periods. The images should provide evidence to support the texts (such as on-site photos), instead of only containing text information that cannot be verified.

Question 1: Is this news forged?
A. Real News
B. Fake News

Question 2: If it's fake news, what type of forgery does it involve?
C. Image Fabrication (There are issues regarding the authenticity of the image. The forgery methods include deepfakes, image splicing, content generated by artificial intelligence, or simulated official media images.)
D. Entity Inconsistency (The image itself is not forged. However, the entities such as characters, places, and things mentioned in the text do not match the content shown in the image. )
E. Event Inconsistency (The image itself is not forged, and there are related entities both in the text and the image. However, usually due to excessive inference and misrepresentation of the accompanying image in the text, the events in the text are inconsistent with those in the image.)
F. Time-Space Inconsistency (The image has not been forged, and the entities or events in the news are consistent, but the time information is different, that is, unmodified images or videos of past events are used to pretend to be recent events for dissemination.)
G. Ineffective Visual Evidence (Encompasses all categories of visual evidence that do not fall under the previously mentioned types)

Answer:"""


MULTI_LABEL_MAP = {
    "0": 5,
    "1": 0,
    "2": 1,
    "3": 2,
    "4": 3,
    "5": 4,
}


def remap_resnet_checkpoint_to_torchvision(state_dict: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
    """
    Convert common wrapped/HuggingFace-style ResNet-34 checkpoints into the
    torchvision naming expected by `torchvision.models.resnet34`.
    """

    remapped: Dict[str, torch.Tensor] = {}
    for key, value in state_dict.items():
        normalized_key = key
        if normalized_key.startswith("resnet."):
            normalized_key = normalized_key[len("resnet.") :]

        if normalized_key == "embedder.embedder.convolution.weight":
            remapped["conv1.weight"] = value
            continue

        if normalized_key.startswith("embedder.embedder.normalization."):
            suffix = normalized_key.split("embedder.embedder.normalization.", 1)[1]
            remapped[f"bn1.{suffix}"] = value
            continue

        stage_match = re.match(
            r"encoder\.stages\.(\d+)\.layers\.(\d+)\.layer\.(\d+)\.(convolution|normalization)\.(.+)",
            normalized_key,
        )
        if stage_match:
            stage_index = int(stage_match.group(1)) + 1
            block_index = int(stage_match.group(2))
            sublayer_index = int(stage_match.group(3)) + 1
            op_type = stage_match.group(4)
            suffix = stage_match.group(5)

            if op_type == "convolution":
                remapped[f"layer{stage_index}.{block_index}.conv{sublayer_index}.{suffix}"] = value
            else:
                remapped[f"layer{stage_index}.{block_index}.bn{sublayer_index}.{suffix}"] = value
            continue

        shortcut_match = re.match(
            r"encoder\.stages\.(\d+)\.layers\.(\d+)\.shortcut\.(convolution|normalization)\.(.+)",
            normalized_key,
        )
        if shortcut_match:
            stage_index = int(shortcut_match.group(1)) + 1
            block_index = int(shortcut_match.group(2))
            op_type = shortcut_match.group(3)
            suffix = shortcut_match.group(4)

            downsample_part = 0 if op_type == "convolution" else 1
            remapped[f"layer{stage_index}.{block_index}.downsample.{downsample_part}.{suffix}"] = value
            continue

        if normalized_key == "classifier.1.weight":
            remapped["fc.weight"] = value
            continue

        if normalized_key == "classifier.1.bias":
            remapped["fc.bias"] = value
            continue

        remapped[normalized_key] = value

    return remapped


def is_wrapped_resnet_checkpoint(state_dict: Dict[str, torch.Tensor]) -> bool:
    keys = list(state_dict.keys())
    return any(
        key.startswith("resnet.embedder.embedder.")
        or key.startswith("embedder.embedder.")
        or key.startswith("resnet.encoder.stages.")
        or key.startswith("encoder.stages.")
        for key in keys
    )


class JsonlImagePromptDataset(Dataset):
    """Dataset that mirrors the user-provided JSONL + image-id convention."""

    def __init__(
        self,
        ann_path: str,
        image_root: str,
        image_extension: str = ".png",
        max_words: int = 800,
        text_source: str = "prompt",
        label_map_mode: str = "paper_multiclass",
    ) -> None:
        self.ann_path = Path(ann_path)
        self.image_root = Path(image_root)
        self.image_extension = image_extension
        self.max_words = max_words
        self.text_source = text_source
        self.label_map_mode = label_map_mode
        self.samples = self._load_jsonl()

    def _load_jsonl(self) -> List[Dict[str, Any]]:
        samples: List[Dict[str, Any]] = []
        with self.ann_path.open("r", encoding="utf-8") as handle:
            raw_text = handle.read().strip()

        if not raw_text:
            return samples

        # Support both jsonl and regular JSON files. Some datasets use a `.json`
        # suffix even though the contents are line-delimited JSON objects.
        try:
            parsed = json.loads(raw_text)
        except json.JSONDecodeError:
            parsed = None

        if parsed is not None:
            if isinstance(parsed, list):
                iterable = parsed
            elif isinstance(parsed, dict):
                iterable = parsed.get("data", parsed.get("annotations", []))
            else:
                raise ValueError(f"Unsupported JSON annotation structure in {self.ann_path}")

            for item in iterable:
                samples.append(self._preprocess_annotation(item))
            return samples

        for line in raw_text.splitlines():
            if not line.strip():
                continue
            item = json.loads(line)
            samples.append(self._preprocess_annotation(item))
        return samples

    def _preprocess_annotation(self, ann: Dict[str, Any]) -> Dict[str, Any]:
        caption = ann.get("content", "")
        caption = re.sub(r"\s{2,}", " ", caption).strip()
        if len(caption) > self.max_words:
            caption = caption[: self.max_words]

        sample_id = ann.get("Id", "unknown")
        raw_label = str(ann.get("label", "0"))
        prompt = TASK_TEMPLATE.format(caption)

        if self.label_map_mode == "paper_multiclass":
            label = MULTI_LABEL_MAP[raw_label]
        elif self.label_map_mode == "raw":
            label = int(raw_label)
        else:
            raise ValueError(f"Unsupported label_map_mode: {self.label_map_mode}")

        return {
            "id": sample_id,
            "caption": caption,
            "prompt": prompt,
            "raw_label": raw_label,
            "label": label,
        }

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, index: int) -> Dict[str, Any]:
        sample = self.samples[index]
        image_path = self.image_root / f"{sample['id']}{self.image_extension}"
        if not image_path.exists():
            raise FileNotFoundError(f"Image not found for sample {sample['id']}: {image_path}")
        image = Image.open(image_path).convert("RGB")
        text = sample["prompt"] if self.text_source == "prompt" else sample["caption"]
        return {
            "id": sample["id"],
            "text": text,
            "label": sample["label"],
            "image": image,
        }


class SyntheticRawDataset(Dataset):
    def __init__(self, num_samples: int, num_classes: int) -> None:
        self.num_samples = num_samples
        self.num_classes = num_classes

    def __len__(self) -> int:
        return self.num_samples

    def __getitem__(self, index: int) -> Dict[str, Any]:
        image = Image.fromarray(np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8))
        text = TASK_TEMPLATE.format(f"Synthetic sample {index}")
        label = index % max(self.num_classes, 1)
        return {
            "id": f"synthetic-{index}",
            "text": text,
            "label": label,
            "image": image,
        }


class MultimodalBatchCollator:
    def __init__(
        self,
        tokenizer: Any,
        image_size: int,
        max_text_tokens: int,
        image_normalization: str = "imagenet",
    ) -> None:
        if transforms is None or InterpolationMode is None:
            raise ImportError("torchvision is required for image preprocessing.")

        image_ops: List[Any] = [
            transforms.Resize((image_size, image_size), interpolation=InterpolationMode.BICUBIC),
            transforms.ToTensor(),
        ]
        if image_normalization == "imagenet":
            image_ops.append(
                transforms.Normalize(
                    mean=(0.485, 0.456, 0.406),
                    std=(0.229, 0.224, 0.225),
                )
            )
        elif image_normalization != "zero_one":
            raise ValueError(f"Unsupported image_normalization: {image_normalization}")

        self.tokenizer = tokenizer
        self.max_text_tokens = max_text_tokens
        self.image_transform = transforms.Compose(image_ops)

    def __call__(self, batch: List[Dict[str, Any]]) -> Dict[str, Any]:
        texts = [item["text"] for item in batch]
        images = [self.image_transform(item["image"]) for item in batch]
        labels = torch.tensor([item["label"] for item in batch], dtype=torch.long)
        sample_ids = [item["id"] for item in batch]

        text_inputs = self.tokenizer(
            texts,
            padding=True,
            truncation=True,
            max_length=self.max_text_tokens,
            return_tensors="pt",
        )

        return {
            "sample_ids": sample_ids,
            "input_ids": text_inputs["input_ids"],
            "attention_mask": text_inputs["attention_mask"],
            "pixel_values": torch.stack(images),
            "labels": labels,
        }


class TFLiteImageEncoder(nn.Module):
    """Run a TFLite image encoder and return a torch tensor feature."""

    def __init__(self, model_path: str, image_normalization: str) -> None:
        super().__init__()
        interpreter_cls = None
        if TFLiteRuntimeInterpreter is not None:
            interpreter_cls = TFLiteRuntimeInterpreter
        elif tf is not None:
            interpreter_cls = tf.lite.Interpreter
        if interpreter_cls is None:
            raise ImportError(
                "A TFLite interpreter is required to use .tflite image encoders. "
                "Install tflite-runtime or tensorflow."
            )

        self.image_normalization = image_normalization
        self.interpreter = interpreter_cls(model_path=model_path)
        self.interpreter.allocate_tensors()
        self.input_details = self.interpreter.get_input_details()[0]
        self.output_details = self.interpreter.get_output_details()[0]

        output_shape = [int(dim) for dim in self.output_details["shape"] if int(dim) > 0]
        if len(output_shape) <= 1:
            self.output_dim = int(output_shape[0])
        else:
            self.output_dim = int(np.prod(output_shape[1:]))

        if self.output_dim != 512:
            raise ValueError(
                f"TFLite image encoder output dim is {self.output_dim}, but CAFE expects a 512-d image feature. "
                "Please provide a TFLite model exported before the final classifier head, or use a PyTorch ResNet-34 checkpoint."
            )

    def _maybe_resize_input(self, np_input: np.ndarray) -> None:
        current_shape = tuple(int(dim) for dim in self.input_details["shape"])
        if current_shape != tuple(np_input.shape):
            self.interpreter.resize_tensor_input(self.input_details["index"], np_input.shape, strict=False)
            self.interpreter.allocate_tensors()
            self.input_details = self.interpreter.get_input_details()[0]
            self.output_details = self.interpreter.get_output_details()[0]

    def _prepare_input(self, pixel_values: torch.Tensor) -> np.ndarray:
        np_input = pixel_values.detach().cpu().numpy()
        input_shape = self.input_details["shape"]
        expects_nhwc = len(input_shape) == 4 and int(input_shape[-1]) == 3
        if expects_nhwc:
            np_input = np.transpose(np_input, (0, 2, 3, 1))

        input_dtype = self.input_details["dtype"]
        if input_dtype == np.uint8:
            if self.image_normalization == "imagenet":
                raise ValueError(
                    "This TFLite model expects uint8 image input, but the profiler is using ImageNet-normalized tensors. "
                    "Please run with --image-normalization zero_one."
                )
            scale, zero_point = self.input_details.get("quantization", (0.0, 0))
            np_input = np.clip(np_input * 255.0, 0.0, 255.0)
            if scale and scale > 0:
                np_input = np.round(np_input / scale + zero_point)
            np_input = np.clip(np_input, 0, 255).astype(np.uint8)
        else:
            np_input = np_input.astype(np.float32)

        return np_input

    def forward(self, pixel_values: torch.Tensor) -> torch.Tensor:
        np_input = self._prepare_input(pixel_values)
        self._maybe_resize_input(np_input)
        self.interpreter.set_tensor(self.input_details["index"], np_input)
        self.interpreter.invoke()
        output = self.interpreter.get_tensor(self.output_details["index"])

        scale, zero_point = self.output_details.get("quantization", (0.0, 0))
        if np.issubdtype(output.dtype, np.integer) and scale and scale > 0:
            output = (output.astype(np.float32) - zero_point) * scale

        output = output.reshape(output.shape[0], -1).astype(np.float32)
        return torch.from_numpy(output).to(pixel_values.device)


class EndToEndCAFEWithEncoders(nn.Module):
    """
    End-to-end inference wrapper for raw text + raw image inputs.

    Text path:
      pretrained text encoder -> per-token projection to 200 dims

    Image path:
      pretrained ResNet-34 -> 512-d visual feature

    Then the current repository's CAFE modules consume those features.
    """

    def __init__(
        self,
        text_encoder_name_or_path: str,
        num_classes: int,
        text_feature_dim: int = 200,
        use_pretrained_image_encoder: bool = True,
        image_encoder_weights_path: Optional[str] = None,
        image_normalization: str = "imagenet",
    ) -> None:
        super().__init__()
        if AutoModel is None or resnet34 is None:
            raise ImportError("transformers and torchvision are required for the raw-input profiler.")

        self.text_encoder = AutoModel.from_pretrained(text_encoder_name_or_path)
        text_hidden_size = int(self.text_encoder.config.hidden_size)
        self.text_projector = nn.Linear(text_hidden_size, text_feature_dim)

        if image_encoder_weights_path and image_encoder_weights_path.endswith(".tflite"):
            self.image_encoder = TFLiteImageEncoder(
                model_path=image_encoder_weights_path,
                image_normalization=image_normalization,
            )
        else:
            if image_encoder_weights_path:
                weights = None
            elif use_pretrained_image_encoder:
                weights = ResNet34_Weights.IMAGENET1K_V1 if ResNet34_Weights is not None else None
            else:
                weights = None
            self.image_encoder = resnet34(weights=weights)
            if image_encoder_weights_path:
                checkpoint = torch.load(image_encoder_weights_path, map_location="cpu")
                state_dict = extract_state_dict(checkpoint)
                if is_wrapped_resnet_checkpoint(state_dict):
                    state_dict = remap_resnet_checkpoint_to_torchvision(state_dict)
                    incompatible = self.image_encoder.load_state_dict(state_dict, strict=False)
                    unexpected_non_fc = [key for key in incompatible.unexpected_keys if not key.startswith("fc.")]
                    missing_non_fc = [key for key in incompatible.missing_keys if not key.startswith("fc.")]
                    if unexpected_non_fc or missing_non_fc:
                        raise RuntimeError(
                            "Failed to remap the provided ResNet checkpoint into torchvision ResNet-34 format. "
                            f"Missing non-fc keys: {missing_non_fc}; unexpected non-fc keys: {unexpected_non_fc}"
                        )
                else:
                    self.image_encoder.load_state_dict(state_dict, strict=True)
            self.image_encoder.fc = nn.Identity()

        self.similarity_module = SimilarityModule()
        self.detection_module = DetectionModule(num_classes=num_classes)

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        pixel_values: torch.Tensor,
    ) -> torch.Tensor:
        text_outputs = self.text_encoder(input_ids=input_ids, attention_mask=attention_mask)
        text_features = self.text_projector(text_outputs.last_hidden_state)
        image_features = self.image_encoder(pixel_values)
        text_aligned, image_aligned, _ = self.similarity_module(text_features, image_features)
        return self.detection_module(text_features, image_features, text_aligned, image_aligned)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Profile multimodal classification inference on jsonl + image datasets."
    )
    parser.add_argument("--ann-path", type=str, default=None, help="Path to the evaluation/test jsonl file.")
    parser.add_argument("--image-root", type=str, default=None, help="Directory containing images named as <Id>.png.")
    parser.add_argument("--image-extension", type=str, default=".png", help="Image file suffix, e.g. .png or .jpg.")
    parser.add_argument(
        "--text-source",
        type=str,
        default="prompt",
        choices=("prompt", "caption"),
        help="Whether to encode the prompt template or the raw caption text.",
    )
    parser.add_argument(
        "--label-map-mode",
        type=str,
        default="paper_multiclass",
        choices=("paper_multiclass", "raw"),
        help="paper_multiclass applies the label remapping from the provided dataset code.",
    )
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--num-classes", type=int, default=6)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--warmup-steps", type=int, default=10)
    parser.add_argument("--single-sample-steps", type=int, default=50)
    parser.add_argument("--max-batches", type=int, default=0, help="0 means use all available batches.")
    parser.add_argument("--max-words", type=int, default=800)
    parser.add_argument("--max-text-tokens", type=int, default=200)
    parser.add_argument("--image-size", type=int, default=224)
    parser.add_argument(
        "--image-normalization",
        type=str,
        default="imagenet",
        choices=("imagenet", "zero_one"),
        help="Image normalization before the image encoder. Use zero_one for most uint8 TFLite models.",
    )
    parser.add_argument("--synthetic-samples", type=int, default=64)
    parser.add_argument(
        "--text-encoder-name-or-path",
        type=str,
        default="bert-base-uncased",
        help="HuggingFace text encoder used as the pretrained text backbone.",
    )
    parser.add_argument(
        "--disable-pretrained-image-encoder",
        action="store_true",
        help="If set, ResNet-34 is initialized without ImageNet weights.",
    )
    parser.add_argument(
        "--resnet34-weights-path",
        type=str,
        default=None,
        help="Optional local ResNet-34 pretrained weights path to avoid auto-download.",
    )
    parser.add_argument("--checkpoint", type=str, default=None, help="Full model checkpoint.")
    parser.add_argument("--text-encoder-checkpoint", type=str, default=None)
    parser.add_argument("--image-encoder-checkpoint", type=str, default=None)
    parser.add_argument("--text-projector-checkpoint", type=str, default=None)
    parser.add_argument("--similarity-checkpoint", type=str, default=None)
    parser.add_argument("--detection-checkpoint", type=str, default=None)
    parser.add_argument(
        "--strict-load",
        action="store_true",
        help="Require exact checkpoint compatibility. Leave unset for transfer-style loading.",
    )
    parser.add_argument(
        "--flops-backend",
        type=str,
        default="auto",
        choices=("auto", "thop", "fvcore", "none"),
    )
    parser.add_argument("--output-json", type=str, default=None)
    return parser.parse_args()


def ensure_runtime_dependencies() -> None:
    missing = []
    if AutoModel is None or AutoTokenizer is None:
        missing.append("transformers")
    if transforms is None or resnet34 is None or InterpolationMode is None:
        missing.append("torchvision")
    if missing:
        raise ImportError("Missing runtime dependencies: " + ", ".join(missing))


def validate_paths(args: argparse.Namespace) -> None:
    if args.ann_path and not Path(args.ann_path).exists():
        raise FileNotFoundError(f"Annotation file not found: {args.ann_path}")
    if args.image_root and not Path(args.image_root).exists():
        raise FileNotFoundError(f"Image root not found: {args.image_root}")
    if args.resnet34_weights_path:
        weight_path = Path(args.resnet34_weights_path)
        if not weight_path.exists():
            raise FileNotFoundError(f"ResNet-34 weights file not found: {args.resnet34_weights_path}")


def is_tensor_state_dict(candidate: Any) -> bool:
    return isinstance(candidate, dict) and candidate and all(torch.is_tensor(v) for v in candidate.values())


def strip_module_prefix(state_dict: Dict[str, Any]) -> Dict[str, Any]:
    return {
        key.replace("module.", "", 1) if key.startswith("module.") else key: value
        for key, value in state_dict.items()
    }


def extract_state_dict(checkpoint_obj: Any) -> Dict[str, Any]:
    if is_tensor_state_dict(checkpoint_obj):
        return strip_module_prefix(checkpoint_obj)

    if isinstance(checkpoint_obj, dict):
        for key in ("state_dict", "model_state_dict", "model", "network", "module"):
            candidate = checkpoint_obj.get(key)
            if is_tensor_state_dict(candidate):
                return strip_module_prefix(candidate)

    raise ValueError("Unable to locate a valid state_dict in the checkpoint.")


def load_state_dict_report(module: nn.Module, state_dict: Dict[str, Any], strict: bool) -> Dict[str, Any]:
    incompatible = module.load_state_dict(state_dict, strict=strict)
    return {
        "missing_keys": list(incompatible.missing_keys),
        "unexpected_keys": list(incompatible.unexpected_keys),
    }


def load_checkpoint_with_report(module: nn.Module, checkpoint_path: str, strict: bool) -> Dict[str, Any]:
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    report = load_state_dict_report(module, extract_state_dict(checkpoint), strict=strict)
    report["path"] = checkpoint_path
    return report


def load_model_weights(model: EndToEndCAFEWithEncoders, args: argparse.Namespace) -> Dict[str, Any]:
    reports: Dict[str, Any] = {
        "strict_load": args.strict_load,
        "loaded": [],
        "encoder_sources": {
            "text_encoder_name_or_path": args.text_encoder_name_or_path,
            "image_encoder": (
                args.resnet34_weights_path
                if args.resnet34_weights_path
                else (
                    "resnet34-imagenet"
                    if not args.disable_pretrained_image_encoder
                    else "resnet34-random-init"
                )
            ),
        },
    }

    if args.checkpoint:
        checkpoint = torch.load(args.checkpoint, map_location="cpu")
        nested_keys = (
            "text_encoder",
            "image_encoder",
            "text_projector",
            "similarity_module",
            "detection_module",
        )
        if isinstance(checkpoint, dict) and any(key in checkpoint for key in nested_keys):
            component_reports: Dict[str, Any] = {"type": "checkpoint:nested_modules", "path": args.checkpoint}
            for key in nested_keys:
                if key in checkpoint:
                    component_reports[key] = load_state_dict_report(
                        getattr(model, key),
                        extract_state_dict(checkpoint[key]),
                        strict=args.strict_load,
                    )
            reports["loaded"].append(component_reports)
        else:
            reports["loaded"].append(
                {
                    "type": "checkpoint:wrapped_model",
                    **load_checkpoint_with_report(model, args.checkpoint, strict=args.strict_load),
                }
            )

    component_paths = {
        "text_encoder": args.text_encoder_checkpoint,
        "image_encoder": args.image_encoder_checkpoint,
        "text_projector": args.text_projector_checkpoint,
        "similarity_module": args.similarity_checkpoint,
        "detection_module": args.detection_checkpoint,
    }
    for name, checkpoint_path in component_paths.items():
        if checkpoint_path:
            reports["loaded"].append(
                {
                    "type": f"checkpoint:{name}",
                    **load_checkpoint_with_report(getattr(model, name), checkpoint_path, strict=args.strict_load),
                }
            )

    return reports


def build_model(args: argparse.Namespace, device: torch.device) -> EndToEndCAFEWithEncoders:
    model = EndToEndCAFEWithEncoders(
        text_encoder_name_or_path=args.text_encoder_name_or_path,
        num_classes=args.num_classes,
        use_pretrained_image_encoder=not args.disable_pretrained_image_encoder,
        image_encoder_weights_path=args.resnet34_weights_path,
        image_normalization=args.image_normalization,
    )
    model.to(device)
    model.eval()
    return model


def build_dataset(args: argparse.Namespace) -> Tuple[Dataset, str]:
    if args.ann_path and args.image_root:
        return (
            JsonlImagePromptDataset(
                ann_path=args.ann_path,
                image_root=args.image_root,
                image_extension=args.image_extension,
                max_words=args.max_words,
                text_source=args.text_source,
                label_map_mode=args.label_map_mode,
            ),
            "jsonl_image_prompt",
        )

    return SyntheticRawDataset(num_samples=args.synthetic_samples, num_classes=args.num_classes), "synthetic"


def build_loader(dataset: Dataset, args: argparse.Namespace) -> DataLoader:
    tokenizer = AutoTokenizer.from_pretrained(args.text_encoder_name_or_path)
    collator = MultimodalBatchCollator(
        tokenizer=tokenizer,
        image_size=args.image_size,
        max_text_tokens=args.max_text_tokens,
        image_normalization=args.image_normalization,
    )
    return DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=torch.cuda.is_available(),
        collate_fn=collator,
    )


def count_parameters(model: nn.Module) -> Dict[str, int]:
    total = sum(parameter.numel() for parameter in model.parameters())
    trainable = sum(parameter.numel() for parameter in model.parameters() if parameter.requires_grad)
    return {
        "params_total": int(total),
        "params_trainable": int(trainable),
    }


def maybe_sync(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.synchronize(device)


def percentile(values: Sequence[float], q: float) -> float:
    if not values:
        return float("nan")
    return float(np.percentile(np.asarray(values, dtype=np.float64), q))


def summarize_ms(values_ms: Sequence[float]) -> Dict[str, float]:
    values = list(values_ms)
    if not values:
        return {
            "mean_ms": float("nan"),
            "std_ms": float("nan"),
            "p50_ms": float("nan"),
            "p90_ms": float("nan"),
            "p95_ms": float("nan"),
        }
    return {
        "mean_ms": float(statistics.mean(values)),
        "std_ms": float(statistics.pstdev(values)) if len(values) > 1 else 0.0,
        "p50_ms": percentile(values, 50),
        "p90_ms": percentile(values, 90),
        "p95_ms": percentile(values, 95),
    }


def current_cuda_memory(device: torch.device) -> Dict[str, Optional[float]]:
    if device.type != "cuda":
        return {
            "cuda_max_memory_allocated_mb": None,
            "cuda_max_memory_reserved_mb": None,
        }
    return {
        "cuda_max_memory_allocated_mb": float(torch.cuda.max_memory_allocated(device) / (1024 ** 2)),
        "cuda_max_memory_reserved_mb": float(torch.cuda.max_memory_reserved(device) / (1024 ** 2)),
    }


def make_forward_inputs(batch: Dict[str, Any]) -> Dict[str, torch.Tensor]:
    return {
        "input_ids": batch["input_ids"],
        "attention_mask": batch["attention_mask"],
        "pixel_values": batch["pixel_values"],
    }


def move_batch_to_device(batch: Dict[str, Any], device: torch.device) -> Dict[str, Any]:
    moved: Dict[str, Any] = {}
    for key, value in batch.items():
        if torch.is_tensor(value):
            moved[key] = value.to(device, non_blocking=True)
        else:
            moved[key] = value
    return moved


def profile_compute_cost(
    model: nn.Module,
    sample_inputs: Tuple[torch.Tensor, torch.Tensor, torch.Tensor],
    backend: str,
) -> Dict[str, Any]:
    selected_backend = backend
    if backend == "auto":
        if thop_profile is not None:
            selected_backend = "thop"
        elif FlopCountAnalysis is not None:
            selected_backend = "fvcore"
        else:
            selected_backend = "none"

    report = {
        "backend": selected_backend,
        "forward_macs": None,
        "forward_flops": None,
        "notes": [],
    }

    if selected_backend == "none":
        report["notes"].append("Install thop or fvcore to enable static compute analysis.")
        return report

    with torch.inference_mode():
        if selected_backend == "thop":
            macs, _ = thop_profile(model, inputs=sample_inputs, verbose=False)
            report["forward_macs"] = float(macs)
            report["forward_flops"] = float(macs * 2.0)
            report["notes"].append("FLOPs are reported as 2 x MACs under the thop convention.")
            return report

        if selected_backend == "fvcore":
            analysis = FlopCountAnalysis(model, sample_inputs)
            flops = analysis.total()
            report["forward_macs"] = float(flops)
            report["forward_flops"] = float(flops * 2.0)
            unsupported = analysis.unsupported_ops()
            if unsupported:
                report["notes"].append(
                    "Unsupported ops skipped by fvcore: "
                    + ", ".join(f"{name} x {count}" for name, count in unsupported.items())
                )
            report["notes"].append("FLOPs are approximated as 2 x fvcore-reported ops.")
            return report

    raise ValueError(f"Unsupported backend: {selected_backend}")


def benchmark_single_sample_forward_latency(
    model: nn.Module,
    sample_inputs: Tuple[torch.Tensor, torch.Tensor, torch.Tensor],
    device: torch.device,
    warmup_steps: int,
    measure_steps: int,
) -> Dict[str, Any]:
    timings_ms: List[float] = []

    if device.type == "cuda":
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats(device)

    with torch.inference_mode():
        for _ in range(max(warmup_steps, 0)):
            _ = model(*sample_inputs)
        maybe_sync(device)

        if device.type == "cuda":
            torch.cuda.reset_peak_memory_stats(device)

        for _ in range(max(measure_steps, 1)):
            maybe_sync(device)
            start = time.perf_counter()
            _ = model(*sample_inputs)
            maybe_sync(device)
            end = time.perf_counter()
            timings_ms.append((end - start) * 1000.0)

    metrics = summarize_ms(timings_ms)
    metrics.update(current_cuda_memory(device))
    return metrics


def benchmark_throughput_and_batch_latency(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    max_batches: int,
) -> Dict[str, Any]:
    forward_batch_latency_ms: List[float] = []
    e2e_batch_latency_ms: List[float] = []
    per_sample_forward_ms: List[float] = []
    total_samples = 0
    total_e2e_seconds = 0.0
    batches_measured = 0

    iterator = iter(loader)

    if device.type == "cuda":
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats(device)

    with torch.inference_mode():
        while True:
            if max_batches and batches_measured >= max_batches:
                break

            e2e_start = time.perf_counter()
            try:
                batch = next(iterator)
            except StopIteration:
                break

            batch = move_batch_to_device(batch, device)
            forward_inputs = make_forward_inputs(batch)
            maybe_sync(device)
            forward_start = time.perf_counter()
            _ = model(**forward_inputs)
            maybe_sync(device)
            forward_end = time.perf_counter()
            e2e_end = time.perf_counter()

            batch_size = int(batch["labels"].shape[0])
            forward_ms = (forward_end - forward_start) * 1000.0
            e2e_ms = (e2e_end - e2e_start) * 1000.0

            forward_batch_latency_ms.append(forward_ms)
            e2e_batch_latency_ms.append(e2e_ms)
            per_sample_forward_ms.append(forward_ms / max(batch_size, 1))
            total_samples += batch_size
            total_e2e_seconds += max(e2e_end - e2e_start, 0.0)
            batches_measured += 1

    return {
        "num_batches_measured": batches_measured,
        "num_samples_measured": total_samples,
        "forward_batch_latency_ms": summarize_ms(forward_batch_latency_ms),
        "e2e_batch_latency_ms": summarize_ms(e2e_batch_latency_ms),
        "forward_sample_latency_mean_ms": float(statistics.mean(per_sample_forward_ms))
        if per_sample_forward_ms
        else float("nan"),
        "eval_samples_per_sec": float(total_samples / total_e2e_seconds)
        if total_e2e_seconds > 0
        else float("nan"),
        "cuda_memory_peak": current_cuda_memory(device),
    }


def safe_format(value: Optional[float]) -> str:
    if value is None:
        return "N/A"
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return "N/A"
    return f"{value:.4f}"


def print_report(report: Dict[str, Any]) -> None:
    print("=== Setup ===")
    print(f"device: {report['setup']['device']}")
    print(f"dataset_mode: {report['setup']['dataset_mode']}")
    print(f"num_classes: {report['setup']['num_classes']}")
    print(f"ann_path: {report['setup']['ann_path']}")
    print(f"image_root: {report['setup']['image_root']}")
    print(f"text_source: {report['setup']['text_source']}")
    print(f"weight_loading: {json.dumps(report['weight_loading'], indent=2)}")
    print("")

    print("=== Compute Cost & Parameters ===")
    print(f"params_total: {report['parameters']['params_total']}")
    print(f"params_trainable: {report['parameters']['params_trainable']}")
    print(f"flops_backend: {report['compute_cost']['backend']}")
    print(f"forward_macs: {report['compute_cost']['forward_macs']}")
    print(f"forward_flops: {report['compute_cost']['forward_flops']}")
    for note in report["compute_cost"]["notes"]:
        print(f"note: {note}")
    print("")

    print("=== Single-Sample Forward Latency ===")
    single = report["single_sample_forward_latency_ms"]
    print(f"mean_ms: {safe_format(single['mean_ms'])}")
    print(f"std_ms: {safe_format(single['std_ms'])}")
    print(f"p50_ms: {safe_format(single['p50_ms'])}")
    print(f"p90_ms: {safe_format(single['p90_ms'])}")
    print(f"p95_ms: {safe_format(single['p95_ms'])}")
    print("")

    print("=== Throughput & Batch Latency ===")
    throughput = report["throughput_and_batch_latency"]
    print(f"num_batches_measured: {throughput['num_batches_measured']}")
    print(f"num_samples_measured: {throughput['num_samples_measured']}")
    print(
        "forward_batch_latency_mean_ms: "
        f"{safe_format(throughput['forward_batch_latency_ms']['mean_ms'])}"
    )
    print(
        "forward_batch_latency_p95_ms: "
        f"{safe_format(throughput['forward_batch_latency_ms']['p95_ms'])}"
    )
    print(
        "e2e_batch_latency_mean_ms: "
        f"{safe_format(throughput['e2e_batch_latency_ms']['mean_ms'])}"
    )
    print(
        "e2e_batch_latency_p95_ms: "
        f"{safe_format(throughput['e2e_batch_latency_ms']['p95_ms'])}"
    )
    print(
        "forward_sample_latency_mean_ms: "
        f"{safe_format(throughput['forward_sample_latency_mean_ms'])}"
    )
    print(f"eval_samples_per_sec: {safe_format(throughput['eval_samples_per_sec'])}")
    print("")

    print("=== VRAM Memory Peak ===")
    memory = report["vram_memory_peak"]
    print(f"cuda_max_memory_allocated_mb: {safe_format(memory['cuda_max_memory_allocated_mb'])}")
    print(f"cuda_max_memory_reserved_mb: {safe_format(memory['cuda_max_memory_reserved_mb'])}")


def main() -> None:
    args = parse_args()
    ensure_runtime_dependencies()
    validate_paths(args)
    device = torch.device(args.device)

    dataset, dataset_mode = build_dataset(args)
    if len(dataset) == 0:
        raise ValueError("Dataset is empty. Check --ann-path and the jsonl contents.")
    loader = build_loader(dataset, args)
    first_batch = next(iter(loader))
    sample_inputs = (
        first_batch["input_ids"][:1].to(device),
        first_batch["attention_mask"][:1].to(device),
        first_batch["pixel_values"][:1].to(device),
    )

    model = build_model(args, device)
    weight_loading = load_model_weights(model, args)

    report = {
        "setup": {
            "device": str(device),
            "dataset_mode": dataset_mode,
            "num_classes": args.num_classes,
            "ann_path": args.ann_path,
            "image_root": args.image_root,
            "text_source": args.text_source,
            "batch_size": args.batch_size,
            "warmup_steps": args.warmup_steps,
            "single_sample_steps": args.single_sample_steps,
            "max_batches": args.max_batches,
        },
        "weight_loading": weight_loading,
        "parameters": count_parameters(model),
        "compute_cost": profile_compute_cost(model, sample_inputs, args.flops_backend),
        "single_sample_forward_latency_ms": benchmark_single_sample_forward_latency(
            model=model,
            sample_inputs=sample_inputs,
            device=device,
            warmup_steps=args.warmup_steps,
            measure_steps=args.single_sample_steps,
        ),
        "throughput_and_batch_latency": benchmark_throughput_and_batch_latency(
            model=model,
            loader=loader,
            device=device,
            max_batches=args.max_batches,
        ),
    }
    report["vram_memory_peak"] = report["throughput_and_batch_latency"]["cuda_memory_peak"]

    print_report(report)

    if args.output_json:
        output_path = Path(args.output_json)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
